linters-settings:
  govet:
    check-shadowing: true
  errcheck:
    check-type-assertions: true
    check-blank: true
  gocyclo:
    min-complexity: 15
  dupl:
    threshold: 100
  goconst:
    min-len: 3
    min-occurrences: 3

linters:
  disable-all: true
  enable:
    - govet
    - errcheck
    - staticcheck
    - gosimple
    - unused
    - ineffassign
    - typecheck
    - gofmt
    - goimports
    - misspell
    - goconst
    - gocyclo
    - dupl

run:
  timeout: 5m
  skip-dirs:
    - vendor
    - .claude

issues:
  exclude-use-default: false
  max-issues-per-linter: 0
  max-same-issues: 0
